FILENAME = ./Architecture/architecture

$(FILENAME).pdf: $(FILENAME).tex

#compiling twice for autogenerated lists
	-pdflatex -interaction=nonstopmode $(FILENAME).tex
	-pdflatex -interaction=nonstopmode $(FILENAME).tex

	rm -f *.aux
	rm -f *.log
	rm -f *.lof
	rm -f *.lot
	rm -f *.out
	rm -f *.toc

diagrams:
	-pdflatex -interaction=nonstopmode ./Architecture/Diagrams/full-modules.tex
	-pdflatex -interaction=nonstopmode ./Architecture/Diagrams/full-modules.tex

	-pdflatex -interaction=nonstopmode ./Architecture/Diagrams/full-workflow.tex
	-pdflatex -interaction=nonstopmode ./Architecture/Diagrams/full-workflow.tex

	rm -f *.aux
	rm -f *.log
	rm -f *.lof
	rm -f *.lot
	rm -f *.out
	rm -f *.toc

idea:
	-pdflatex -interaction=nonstopmode ./Idea/ladders.tex
	-pdflatex -interaction=nonstopmode ./Idea/ladders.tex

	rm -f *.aux
	rm -f *.log
	rm -f *.lof
	rm -f *.lot
	rm -f *.out
	rm -f *.toc

idea-notes:
	-pdflatex -interaction=nonstopmode ./Idea/ladders-notes.tex
	-pdflatex -interaction=nonstopmode ./Idea/ladders-notes.tex

	rm -f *.aux
	rm -f *.log
	rm -f *.lof
	rm -f *.lot
	rm -f *.out
	rm -f *.toc

clean:
	rm -f architecture.pdf
	rm -f full-modules.pdf
	rm -f full-workflow.pdf
	rm -f ladders.pdf
	rm -f ladders-notes.pdf

.PHONY: diagrams, idea, idea-notes, clean
